services:
  backend:
    build:
      context: ./backend
    container_name: portal_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/portfolio
    depends_on:
      - mongo
  nginx:
    image: nginx
    container_name: nginx_service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/index.html:/usr/share/nginx/html

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portal_frontend
    ports:
      - 4173:4173
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongo:/data/db
      #- /c/Users/Uddhav/Documents/Databases/portal-data:/data/db
      
volumes:
  mongo-data: