version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/portfolio
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "4174:4174"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /c/Users/Uddhav/Documents/Databases/portal-data:/data/db

volumes:
  mongo-data: